export const refs = {
  currencyRate: document.querySelector('[data-currency-rate="currency-rate"]'),
  form: document.querySelector('form'),
  formGroup: document.querySelector('.form-group'),
  submitButton: document.querySelector('[type="submit"]'),
  widthInput: document.querySelector('[data-input="width"]'),
  heightInput: document.querySelector('[data-input="height"]'),
  inputInfoButton: document.querySelector('.input-info'),
  addButton: document.querySelector('.add-button'),
  removeButton: document.querySelector('.remove-button'),
  optionButton: document.querySelector('[data-option="1"]'),
  closeModalButton: document.querySelector('[data-modal-close]'),
  modalBlock: document.querySelector('[data-modal]'),
  marginButton: document.querySelector('[data-action="margin"]'),
};
